name: watcher
version: 1.1.0
description: >-
  A file system watcher. It monitors changes to contents of directories and
  sends notifications when files have been added, removed, or modified.
repository: https://github.com/dart-lang/watcher

environment:
  sdk: ^3.0.0

dependencies:
  async: ^2.5.0
  path: ^1.8.0

dev_dependencies:
  benchmark_harness: ^2.0.0
  dart_flutter_team_lints: ^1.0.0
  test: ^1.16.0
  test_descriptor: ^2.0.0

