name: watcher
version: 0.10.0-nullsafety.0

description: >-
  A file system watcher. It monitors changes to contents of directories and
  sends notifications when files have been added, removed, or modified.
repository: https://github.com/dart-lang/watcher

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  async: ^2.5.0-nullsafety.3
  path: ^1.8.0-nullsafety.3
  pedantic: ^1.10.0-nullsafety.3

dev_dependencies:
  benchmark_harness: ^2.0.0-nullsafety.0
  test: ^1.16.0-nullsafety.13
  test_descriptor: ^2.0.0-nullsafety

dependency_overrides:
  analyzer: ^0.41.1
